#!/bin/bash

read -p "Name (Name on server and Loadname): " NAME
echo "name: $NAME" > ~/Steam/st600760/settings

read -p "Worldtype (Mars, Moon or Space): " TYPE
echo "type: $TYPE" >> ~/Steam/st600760/settings

read -p "Password (Server login password): " PASWD
echo "password: $PASWD" >> ~/Steam/st600760/settings

read -p "Servername (Server name ingame): " SERVN
echo "servername: $SERVN" >> ~/Steam/st600760/settings

#servername:
#worldname: MarsZA02
#worldtype: Mars
#password: Super.007
