#!/bin/bash

ROOTP=$(cd "${0%/*}" && echo $PWD)

stop_server () {
	$ROOTP/stop >> /dev/null 2>&1
}

# CONFIG FILE
# -----------
config_update () {
	if [ ! -f $ROOTP/config ]
	then
		touch $ROOTP/config
		FIRSTRUN=y
	else
		FIRSTRUN=n
		echo "File exist already"
		read -p "Update (y/n)? Enter for (y) :" UPDATE
		if [ -z "$UPDATE" ]
		then
			UPDATE=y
		elif [ $UPDATE = y ]
		then
			UPDATE=y
		elif [ $UPDATE = n ]
		then
			UPDATE=n
		fi
		if [ $UPDATE = y ]
		then
			P_BETA=$(cat $ROOTP/config | grep beta: | awk '{ print $2 }')
			P_SECURE=$(cat $ROOTP/config | grep secure: | awk '{ print $2 }')
			P_WORLDNAME=$(cat $ROOTP/config | grep worldname: | awk '{ print $2 }')
			P_WORLDTYPE=$(cat $ROOTP/config | grep worldtype: | awk '{ print $2 }')
			P_PASSWORD=$(cat $ROOTP/config | grep password: | awk '{ print $2 }')
			P_SERVERNAME=$(cat $ROOTP/config | grep servername: | awk '{ print $2 }')
		else
			UPDATE=n
		fi
	fi
}


# Q1
# --
Q1_Beta () {
	read -p "Play Beta (y/n)? Enter for(n) :" BETA
	if [ -z "$BETA" ]
	then
		BETA=n
	elif [ $BETA = n ]
	then
		BETA=n
	elif [ $BETA = y ]
	then
		BETA=y
	fi
	if [ $BETA = y ]
	then
		echo "beta: yes" >> $ROOTP/config
	else
		echo "beta: no" >> $ROOTP/config
	fi
}


# Q2
# --
Q2_Worldname () {
	read -p "Worldname? " WORLDNAME
	echo "worldname: $WORLDNAME" >> $ROOTP/config
}


# Q3
# --
Q3_Worldtype () {
	echo "1 = Moon"
	echo "2 = Mars"
	echo "3 = Space"
	echo "4 = Europa"
	read -p "Worldtype (1,2,3,4): " WORLDTYPE

	if [ $WORLDTYPE = 1 ]
	then
		echo "worldtype: Moon" >> $ROOTP/config
	elif [ $WORLDTYPE = 2 ]
	then
		echo "worldtype: Mars" >> $ROOTP/config
	elif [ $WORLDTYPE = 3 ]
	then
		echo "worldtype: Space" >> $ROOTP/config
	elif [ $WORLDTYPE = 4 ]
	then
		echo "worldtype: Europa" >> $ROOTP/config
	else
		echo "Invalid option ($WORLDTYPE)"
	fi
}


# Q4
# --
Q4_Servername () {
	read -p "Servername: " SERVERNAME
	echo "servername: $SERVERNAME" >> $ROOTP/config
}


# Q5
# --
Q5_Secure () {
	read -p "Password Protect server (y/n)? Enter for (n): " SECURE
	if [ -z "$SECURE" ]
	then
		SECURE=n
	elif [ $SECURE = n ]
	then
		SECURE=n
	elif [ $SECURE = y ]
	then
		SECURE=y
	fi
	if [ $SECURE = y ]
	then
		echo "secure: yes" >> $ROOTP/config
		read -p "Password: " PASSWORD
		echo "password: $PASSWORD" >> $ROOTP/config
	else
		echo "secure: no" >> $ROOTP/config
		echo "password: " >> $ROOTP/config
	fi
}

config_update

if [ $FIRSTRUN = y ]
then
	Q1_Beta
	Q2_Worldname
	Q3_Worldtype
	Q4_Servername
	Q5_Secure
else
	if [ $UPDATE = y ]
	then
		cp $ROOTP/config $ROOTP/config.back
		rm $ROOTP/config && touch $ROOTP/config
		echo ""
		echo "-------- Beta ----------"
		echo ""
		echo "Current setting: $P_BETA"
		read -p "Keep Current setting (y/n)? Enter for (y) :" KEEP
		if [ -z "$KEEP" ]
		then
			KEEP=y
		elif [ $KEEP = y ]
		then
			KEEP=y
		elif [ $KEEP = n ]
		then
			KEEP=n
		fi
		if [ $KEEP = y ]
		then
			echo "beta: $P_BETA" >> $ROOTP/config
		else
			Q1_Beta
		fi

		echo ""
		echo "-------- Worldname ----------"
		echo ""
		echo "Current setting: $P_WORLDNAME"
		read -p "Keep Current setting (y/n)? Enter for (y) :" KEEP
		if [ -z "$KEEP" ]
		then
			KEEP=y
		elif [ $KEEP = y ]
		then
			KEEP=y
		elif [ $KEEP = n ]
		then
			KEEP=n
		fi
		if [ $KEEP = y ]
		then
			echo "worldname: $P_WORLDNAME" >> $ROOTP/config
		else
			Q2_Worldname
		fi

		echo ""
		echo "-------- Worldtype ----------"
		echo ""
		echo "Current setting: $P_WORLDTYPE"
		read -p "Keep Current setting (y/n)? Enter for (y) :" KEEP
		if [ -z "$KEEP" ]
		then
			KEEP=y
		elif [ $KEEP = y ]
		then
			KEEP=y
		elif [ $KEEP = n ]
		then
			KEEP=n
		fi
		if [ $KEEP = y ]
		then
			echo "worldtype: $P_WORLDTYPE" >> $ROOTP/config
		else
			Q3_Worldtype
		fi

		echo ""
		echo "-------- Servername ----------"
		echo ""
		echo "Current setting: $P_SERVERNAME"
		read -p "Keep Current setting (y/n)? Enter for (y) :" KEEP
		if [ -z "$KEEP" ]
		then
			KEEP=y
		elif [ $KEEP = y ]
		then
			KEEP=y
		elif [ $KEEP = n ]
		then
			KEEP=n
		fi
		if [ $KEEP = y ]
		then
			echo "servername: $P_SERVERNAME" >> $ROOTP/config
		else
			Q4_Servername
		fi

		echo ""
		echo "-------- Secure ----------"
		echo ""
		echo "Current setting: $P_SECURE"
		read -p "Keep Current setting (y/n)? Enter for (y) :" KEEP
		if [ -z "$KEEP" ]
		then
			KEEP=y
		elif [ $KEEP = y ]
		then
			KEEP=y
		elif [ $KEEP = n ]
		then
			KEEP=n
		fi
		if [ $KEEP = y ]
		then
			echo "secure: $P_SECURE" >> $ROOTP/config
			echo "password: $P_PASSWORD" >> $ROOTP/config
		else
			Q5_Secure
		fi
	fi
fi 



# Q6
## --
#echo "1 = Survival"
#echo "2 = Creative"
#read -p "Game Mode (1,2): " GAMEMODE
#if [ $GAMEMODE = 1 ]
#then
#	echo "gamemode: Survival" >> $ROOTP/config
#elif [ $GAMEMODE = 2 ]
#then
#	echo "gamemode: Creative" >> $ROOTP/config
#fi


# SHOW SETTINGS
# -------------
echo ""
echo "----------------------------------------------"
cat $ROOTP/config
echo "----------------------------------------------"
echo ""

