#!/bin/bash

read -p "New RCONPASSWORD: " RCONPASSWORD

RCONFILE="/usr/local/steamgame_600760/server/default.ini"
RCON_DSET=$(cat $RCONFILE | sed '/RCONPASSWORD/d')
echo "$RCON_DSET" > $RCONFILE
echo "RCONPASSWORD=$RCONPASSWORD" >> $RCONFILE
cat $RCONFILE