#!/bin/bash

ROOTP=$(cd "${0%/*}" && echo $PWD)

# STOP PREVIOUS SERVERS
# ---------------------
$ROOTP/stop >> /dev/null 2>&1

# VARIABLES
# ---------
SECURE=$(cat $ROOTP/config | grep secure: | awk '{ print $2 }')
WORLDNAME=$(cat $ROOTP/config | grep worldname: | awk '{ print $2 }')
WORLDTYPE=$(cat $ROOTP/config | grep worldtype: | awk '{ print $2 }')
PASSWORD=$(cat $ROOTPconfig | grep password: | awk '{ print $2 }')
SERVERNAME=$(cat $ROOTP/config | grep servername: | awk '{ print $2 }')

#########################################################################################################################

if [ $SECURE = yes ]
then
	echo "------------------------------------------"
	echo
	echo "Secure: $SECURE"
	echo "Name: $WORLDNAME"
	echo "Type $WORLDTYPE"
	echo "Password: $PASSWORD"
	echo "Servername: $SERVERNAME"
	echo
	echo "------------------------------------------"

	/usr/local/steamgame_600760/rocketstation_DedicatedServer.x86_64 \
        -autostart \
        -batchmode \
        -nographics \
        -password=$PASSWORD \
        -autosaveinterval=300 \
        -clearallinterval=65535 \
        -loadworld=$WORLDNAME \
        -worldtype=$WORLDTYPE \
        -worldname=$WORLDNAME \
        -servername=$SERVERNAME \
        -basedirectory=server/ \
        &

elif [ $SECURE = no ]
then
	echo "------------------------------------------"
	echo
	echo "Secure: $SECURE"
	echo "Name: $WORLDNAME"
	echo "Type $WORLDTYPE"
	echo "Servername: $SERVERNAME"
	echo
	echo "------------------------------------------"

	/usr/local/steamgame_600760/rocketstation_DedicatedServer.x86_64 \
        -autostart \
        -batchmode \
        -nographics \
        -autostart \
        -updateport 27015 \
        -gameport 27016 \
        -autosaveinterval=300 \
        -clearallinterval=65535 \
        -loadworld=$WORLDNAME \
        -worldtype=$WORLDTYPE \
        -worldname=$WORLDNAME \
        -servername=$SERVERNAME \
        -basedirectory=server/ \
        &
else
        echo "ERROR"
fi