#!/bin/bash

# VARIABLES
# ---------
NAME=$(cat ~/Steam/st600760/settings | grep name: | awk '{ print $2 }')
TYPE=$(cat ~/Steam/st600760/settings | grep type: | awk '{ print $2 }')
PASWD=$(cat ~/Steam/st600760/settings | grep password: | awk '{ print $2 }')
SERVN=$(cat ~/Steam/st600760/settings | grep servername: | awk '{ print $2 }')

echo "------------------------------------------"
echo
echo "Name: $NAME"
echo "Type $TYPE"
echo "Password: $PASWD"
echo "Servername: $SERVN"
echo
echo "------------------------------------------"

# COMMAND
# -------
/root/Steam/steamapps/common/Stationeers\ Dedicated\ Server/rocketstation_DedicatedServer.x86_64 \
	-autostart \
	-batchmode \
	-nographics \
	-password=$PASWD \
	-autosaveinterval=300 \
	-clearallinterval=65535 \
	-loadworld=$NAME \
	-worldtype=$TYPE \
	-worldname=$NAME \
	-servername=$SERVN \
	-basedirectory=~/Steam/ \
	&
