#!/bin/bash

echo "Worlname: 	$(cat /root/stationeers_servers/serversettings | grep worldname: | awk '{ print $2 }')"
echo "PID: 		$(/usr/bin/ps aux | grep -e $(cat /root/stationeers_servers/serversettings | grep worldname: | awk '{ print $2 }') | grep -v grep | awk '{ print $2 }')"

