#!/bin/bash

# STOP SERVER
# -----------
~/Steam/st600760/stop >> /dev/null 2>&1


# BACKUP SERVER
# -------------
#~/Steam/st600760/backup


# UPDATE SERVERS
# --------------
BETA=$(cat ~/Steam/st600760/settings | grep beta: | awk '{ print $2 }')
if [ $BETA = yes ]
then
echo "BETA"
~/Steam/steamcmd.sh +login anonymous +app_update 600760 validate +quit
else
echo "STANDARD"
~/Steam/steamcmd.sh +login anonymous +app_update 600760 validate +quit
fi

# COPY MINING MOD
# ---------------

#rm -f /root/Steam/steamapps/common/Stationeers\ Dedicated\ Server/rocketstation_DedicatedServer_Data/StreamingAssets/Data/mineables.xml
#cp /root/stationeers_servers/mineables.xml /root/Steam/steamapps/common/Stationeers\ Dedicated\ Server/rocketstation_DedicatedServer_Data/StreamingAssets/Data/
#cat /root/Steam/steamapps/common/Stationeers\ Dedicated\ Server/rocketstation_DedicatedServer_Data/StreamingAssets/Data/mineables.xml | grep MinDropQuantity


# START SERVER
# ------------
#echo
~/Steam/st600760/start
