#!/bin/bash

ROOTP=$(cd "${0%/*}" && echo $PWD)

# STOP SERVER
# -----------
$ROOTP/stop >> /dev/null 2>&1


# BACKUP SERVER
# -------------
#$ROOTP/backup


# UPDATE SERVERS
# --------------
BETA=$(cat $ROOTP/config | grep beta: | awk '{ print $2 }')
if [ $BETA = yes ]
then
echo "BETA"
~/Steam/steamcmd.sh +login anonymous +app_update 600760 validate +quit
else
echo "STANDARD"
~/Steam/steamcmd.sh +login anonymous  +force_install_dir /usr/local/steamgame_600760/ +app_update 600760 validate +quit
fi

# COPY MINING MOD
# ---------------

#rm -f /root/Steam/steamapps/common/Stationeers\ Dedicated\ Server/rocketstation_DedicatedServer_Data/StreamingAssets/Data/mineables.xml
#cp /root/stationeers_servers/mineables.xml /root/Steam/steamapps/common/Stationeers\ Dedicated\ Server/rocketstation_DedicatedServer_Data/StreamingAssets/Data/
#cat /root/Steam/steamapps/common/Stationeers\ Dedicated\ Server/rocketstation_DedicatedServer_Data/StreamingAssets/Data/mineables.xml | grep MinDropQuantity


# START SERVER
# ------------
#echo
#$ROOTP/start
